### PR TITLE
Add Code Climate badge and fix TravisCI broken link

### PR DESCRIPTION
**Pull request by hugoabonizio**
Nice project, guys! :smiley:

### CODE REVIEW

**Comment by marceloboeira** [comment]
A wild @hugoabonizio appears!

**Comment by marceloboeira** [comment]
@hugoabonizio thanks for the PR.

Some regards:
 - `fix: ...` -> is more for code-bugs, documentation is always Doc.
 - Not sure if it is mentioned but we should try to always use verbs, you pretty much did that 👍 

e.g:
`fix: TravisCI link` -> `doc: Fix TravisCI link at the README`

But there is no need to change it now, just a soft-reminder for the future 👍 

Thanks a lot dude!

**Comment by hugoabonizio** [comment]
Hi @marceloboeira!

Thank you for the advice, I'm still getting used to semantic commits :smile:

**Comment by marceloboeira** [comment]
@hugoabonizio don't worry dude! You are doing a nice job already. 👍

**Comment by marceloboeira** [comment]
@hugoabonizio I have invited you to the slack and github teams 🤓

**Comment by hugoabonizio** [comment]
@marceloboeira Thanks!

**Pull request merged**
